import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/providers/app-provider";
import { Toaster } from "sonner";
import NextTopLoader from 'nextjs-toploader';

const manrope = Manrope({
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased bg-[#f4f4f4]`}>
        <AppProvider>
          <NextTopLoader color="#4d0eb9" showSpinner={false} />
          {children}
        </AppProvider>
        <Toaster />
      </body>
    </html>
  );
}
